### ISSUE TITLE
Deploy url is not actual url

### ISSUE THREAD

**Issue by AlexProgrammerDE** [product-os/landr#306]
This is my log:
[landr] Deploying site to https://landr-balena-io--landr-preview-patch-2.netlify.com
[landr] Deployed with Landr v5.30.5
[landr] Visit https://landr-balena-io-landr-preview-patch-2.netlify.com
[landr] Head over to https://app.netlify.com/sites/landr-balena-io--landr-preview-patch-2/settings/domain/setup to setup a different domain

These are not the same:
https://landr-balena-io--landr-preview-patch-2.netlify.com
https://landr-balena-io-landr-preview-patch-2.netlify.com

**Comment by LucianBuzzo** [comment]
@AlexProgrammerDE This was fixed in v5.31.0 https://github.com/product-os/landr/commit/4b71b9aa9d99b050b3606596112245e781eee727#diff-e2a46d3c5c3e72a2ddd20518f32e5ac9R73
