### ISSUE TITLE
Logo image squished on mobile views

### ISSUE THREAD

**Issue by nucleardreamer** [product-os/landr#385]
On mobile, the logo image appears to squish its aspect ratio by default:

![image](https://user-images.githubusercontent.com/1727112/129799077-12cd1a31-6753-4dca-bff0-7480c3f6516f.png)

**Comment by iamsolankiamit** [comment]
@nucleardreamer no longer an issue. The sense project need a new rebuild with latest landr version, you can see how sound looks which is built with a recent landr version.

<img width="422" alt="Screenshot 2022-04-06 at 11 53 36 PM" src="https://user-images.githubusercontent.com/3483526/162042741-d1bdcd6b-ffc1-4ffc-97d8-ace681b1f37c.png">
