### ISSUE TITLE
The state of react-static -- and its inevitable death

### ISSUE THREAD

**Issue by fisehara** [product-os/landr#493]
Here is a outlook for the react-static project that it will loose it's main contributors:
https://github.com/react-static/react-static/discussions/1661

> When my company took over development of react-static, we quickly solved a lot of outstanding issues and a highly active team of contributors pumped out even more fixes and upgrades to the current codebase. This was great.
> 
> Then COVID happened.
> 
> During the first months of COVID-19, we lost 80% of our recurring income, most of whomstve were running on react-static. Not only did we have to scramble for more work, the work we found was very different and did not need react-static at all. You may have seen me comment on various issues that we were struggling during COVID keeping this alive, because we had an extremely high workload to keep the company alive, without a single paying client funding this work.
> 
> Fast-forward to 2022.
> 
> We are doing great as a company (with more work offers than we can take on), but not a single company that left us came back after COVID. The majority of which were US-based and are still struggling, whereas our EU-based clients (now > 75%) are all doing very well. Because there is no funding for react-static, and there is literally not a single reason for us to keep investing in it, I'm going to let go of the project.
> 
> I understand this is still a helpful tool for some people, and we have no intentions of purging it from existence, but there is just no economic viability.
> 
> For the projects where we normally had used react-static, we now use [remix](https://remix.run/), and https://nextjs.org/ for others.
> 
> Feel free to leave your thoughts here, but if you have time to spare, instead, see what you can do to help Ukraine, including supporting those Russians who are against the war.

**Comment by iamsolankiamit** [comment]
@fisehara awesome thanks, I didn't checkout react-static recently. it is working as expected for us, so we don't have a huge problem.

This does point out that we should look for better or more maintained solutions or maintain react-static ourselves ( given that it works for us and is not much of a hindrance)
